"""update document uploader to foreign key

Revision ID: 2dc45d98bdda
Revises: bde1d06a564d
Create Date: 2026-05-28 10:55:14.578780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc45d98bdda'
down_revision: Union[str, Sequence[str], None] = 'bde1d06a564d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('documents', sa.Column('uploader_id', sa.Integer(), nullable=False))
    # 1. 新增欄位，先設定 nullable=True (允許為空)，避免舊資料報錯
    op.add_column('documents', sa.Column('uploader_id', sa.Integer(), nullable=True))

    # --- 💡 你必須手動加入的「資料過渡」邏輯 ---
    # 2. 將舊文件的 uploader_id 全部預設為 1
    op.execute("UPDATE documents SET uploader_id = 1")
    
    # 3. 資料填滿後，再把欄位鎖緊變成「不可為空」
    op.alter_column('documents', 'uploader_id', nullable=False)
    op.create_foreign_key(None, 'documents', 'users', ['uploader_id'], ['id'])
    op.drop_column('documents', 'uploader')
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    

    # 1. 加回舊的字串欄位 (先允許為空)
    op.add_column('documents', sa.Column('uploader', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # 2. 隨便塞個假名字回去，確保資料完整性
    op.execute("UPDATE documents SET uploader = 'system_restore'")
    
    # 3. 改回不可為空
    op.alter_column('documents', 'uploader', nullable=False)

    # 4. 刪除 Foreign Key 關聯
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # 5. 刪除整數欄位
    op.drop_column('documents', 'uploader_id')

    # ### end Alembic commands ###
