"""restrict documents table column length

Revision ID: 5eeda01ba24a
Revises: a0dfd371adbb
Create Date: 2026-05-28 09:40:01.693044

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5eeda01ba24a'
down_revision: Union[str, Sequence[str], None] = 'a0dfd371adbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    status_enum = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='documentstatus')
    status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('documents', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='documentstatus'),
    #            nullable=False)
    # ### end Alembic commands ###
    # 3. 使用原生 SQL 執行變更，並加上 USING 語法，告訴資料庫如何把舊字串轉成 Enum
    op.execute("ALTER TABLE documents ALTER COLUMN status TYPE documentstatus USING status::text::documentstatus")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('documents', 'status',
    #            existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='documentstatus'),
    #            type_=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###
    # 1. 先把欄位轉回一般的 VARCHAR (String)
    op.execute("ALTER TABLE documents ALTER COLUMN status TYPE VARCHAR USING status::text")
    
    # 2. 再把剛剛創造的 Enum 型別從資料庫裡徹底刪除
    status_enum = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='documentstatus')
    status_enum.drop(op.get_bind())
